### ISSUE TITLE
/account/:id/unlock of a non existent account differs in behavior from fxa-auth-db-mem

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-db-mysql#11]
The MySQL driver succeeds whereas the memory driver fails with a 404 (not found).

**Comment by chilts** [comment]
You're right. I think the problem area is the `MySql.prototype.write()` in `db/mysql.js`.

Basically, it always returns `{}` if the query was successfully executed, whether or not any rows have been affected. I thought I had raised this before somewhere ... ah yes, here : https://github.com/mozilla/fxa-auth-db-server/issues/47

So I suspect it's happening in a couple of different places. So, let's figure out a little plan:

1. `.write()` should return something about the result of the query (see below)
1. `.write()` is called in a number of places so each of those places will need to decide whether to just: (1) return the `{}` as it currently does, or (2) inspect the result and return something else if necessary

If we're essentially going to change a possible `200 - {}` to a `404 - {"message":"Not Found"}` are we happy that the current clients won't barf with this change?

**Comment by chilts** [comment]
For reference, the `result` in `.write()` for a query which affects zero rows looks like:

```json
{
    fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0
}
```

See here for the difference between `affectedRows` and `changedRows` : https://www.npmjs.com/package/mysql#getting-the-number-of-affected-rows (from running the tests with that result logged, it looks like `changedRows` is always zero for our uses, whereas `affectedRows` is always 0, 1 or 2).

**Comment by chilts** [comment]
This is interesting so far.

I have some changes to mysql.js and to the backend tests so that successful operations (for things like deleteSomething) continue to return an empty object as is the case now, but will throw a `error.notFound()` to break the promise if nothing happened. It seems ok.

From what I can tell for things like `.verifyEmail()` the results we get back contain something very similar to the above. ie. a datastructure with these fields populated. This is a plain stored procedure with no transaction doing just one update. The results reflect that one update.

However, when calling `.lockAccount()` (and by no means the only one since others will likely reflect this), the returned datastructure from the mysql driver contains the above fields, but neither `affectedRows` or `changedRows` are ever set. This is weird because the docs say that multiple results sets can be returned : https://www.npmjs.com/package/mysql#stored-procedures

Theory: the "multiple results sets" are most likely the result of multiple SELECTs and not (as in this case) the result of a REPLACE and an UPDATE. It seems that because they don't return a set of rows, then they don't produce a "multiple result set". My other theory then goes, since the result of these two operations *should* be reflected in the resulting information (as above), they either overwrite one another, or the final `COMMIT` overwrites this information or gobbles it up. And of course, even if the COMMIT didn't do that, we'd only be able to get the result of one of those two queries.

Yes, this is all just theory at the moment, but am writing it down whilst it's fresh in my brain. It's been a bit Sherlock Holmes today, so I'll carry on tomorrow as Dr. Watson.

**Comment by rfk** [comment]
There may be some magic to make the stored procedure explicitly return a particular result

**Comment by dannycoates** [comment]
Ignoring the implementation details of either mysql or mem, what is the desired behavior, "not found" or "sure, whatever"?

Looking at the app code it kind of seems like it doesn't matter much. https://github.com/shane-tomlinson/fxa-auth-server/blob/account-lockout/routes/account.js#L581-L611

Its not very likely the account will get deleted between looking it up on line 585 and unlocking on 600, but even if it did, who cares? So, I think I'm in favor of the "sure, whatever" response as the "correct" response.

**Comment by chilts** [comment]
As a side note, if I change the stored procedure from this structure, to the following, I can get data back and act on that to see if we did anything:

```sql
START TRANSACTION;
REPLACE INTO ...
UPDATE ...
COMMIT;
```

```sql
START TRANSACTION;
SELECT count(uid) AS count FROM account WHERE uid = inUid;
REPLACE INTO ...
UPDATE ...
COMMIT;
```

This will give me that multiple result set and tell me if the account exists (a count of one) or doesn't (a count of zero).

This feels hacky but it does work. Essentially the result set only comes back from SELECTs and the result of things like `affectedRows` or `changedRows` are just the result of the last statement (in this case the COMMIT).

**Comment by chilts** [comment]
@dannycoates your comment above is slightly different to what is in https://github.com/mozilla/fxa-auth-db-server/issues/47 but they are for different operations admittedly.

Does this mean we're going with the approach of whatever feels right for which operation? ie. not necessarily consistent (and actually sometimes dependent on the implementation detail of whether the stored procedure has a transaction or not).

I don't think I'm a fan of this and would prefer to be consistent. Either always say 'whatever' or always '404', across all of these operations, not just this one. I don't know.

So:

1. always 404
2. always 'whatever'
3. depends on the operation and whether we can get that info returned from MySql (or force it to be returned)

:ok: :+1: :-1: :question: :do_not_litter:

**Comment by dannycoates** [comment]
> Does this mean we're going with the approach of whatever feels right for which operation?

I think we can be consistent, but I'm not sure throwing `notFound` on updates is what we really want anymore. I hadn't given it much thought until now.

It all depends on whether we choose to consider an update to a null record an error or not. Its interesting that the two implementations we have inherently make the opposite choice and that both are reasonable. I'm probably in the no-op camp now because given the choice between having to handle a benign error and never knowing about it, I'd choose ignorance, but I could be convinced otherwise.

**Comment by dannycoates** [comment]
P.S. the "no error" case seems like it would work better for any eventually consistent databases

**Comment by chilts** [comment]
It sounds like for the purposes of `/account/:id/unlock`, let's go with 'sure, whatever'. This is easier for the mysql backend (no changes) and only a slight change for the mem backend.

If we resolve this operation now, we can get @shane-tomlinson's locked account work merged. Perhaps we can revisit the other operations later. Pipe up if you have any different suggestions. If not, I'll create a ticket in db-mem to change it's behaviour.

@shane-tomlinson's are you happy that unlocking a non-existant account would be a `200 - {}` rather than a `404 - {"message":"Not Found"}`? I think in another issue we were tending towards the being explicit error messages to the client but perhaps we're not.

(Note: I think there are a few different ideas here at the moment on the way forward, so I'm just trying to figure out which way to go.)

**Comment by rfk** [comment]
Yeah, let's push ahead with "sure, whatever" for now and we can follow up on more nuanced behaviour in smaller PRs.  The lockout stuff is big and sprawling enough as it is :-)

**Comment by chilts** [comment]
Cool.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson's are you happy that unlocking a non-existant account would be a 200 - {} rather than a 404 - {"message":"Not Found"}? I think in another issue we were tending towards the being explicit error messages to the client but perhaps we're not.

This sounds good to me. After giving this some more thought, this approach is probably preferable. In the auth server, we already check the account to see if it has a `lockedAt` value. If not, [we silently succeed](https://github.com/mozilla/fxa-auth-server/pull/867/files#diff-43da5bcdd83eb1d30aa0b5e9e7473834R588). If the database has not gone haywire and everything is consistent, we should not see a 404 if that first check has passed.

**Comment by shane-tomlinson** [comment]
@chilts merged the fix for this, closing.
