### ISSUE TITLE
/account/reset sometimes fails with 'invalid token'

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#149]
Sometimes `/account/reset` starts failing for no apparent reason. It seems to fail more often on @shane-tomlinson's machine than on mine. Once it starts to fail, it continues doing so until the db server is restarted. Re-starting the auth server at that point has no effect.

This has been happening for a long time, but may have become more frequent recently. We've only seen it happen when running against the memory backend, although that doesn't necessarily mean the problem is there.

In the auth server logs, the `uid` in the failing request payload is always a null byte / `00`. In the db server logs, there is a `SyntaxError: Unexpected token ILLEGAL`.

auth server log:

![auth-server-logs](https://cloud.githubusercontent.com/assets/64367/17209106/52467566-54b3-11e6-8ddd-bfc51c4cb7ca.png)

db server log:

![auth-db-logs](https://cloud.githubusercontent.com/assets/64367/17209116/5912aa36-54b3-11e6-8476-e4692989c51d.png)

db server syntax error:

![auth-db-with-compile-error](https://cloud.githubusercontent.com/assets/64367/17209126/5e3fc8ea-54b3-11e6-9657-a47572d66570.png)

**Comment by philbooth** [comment]
@shane-tomlinson reports that, when debugging, he can see there is a token that gets initialised with a `createdAt` in the past.

**Comment by rfk** [comment]
Sounds super weird.  When you say:

> Sometimes /account/reset starts failing for no apparent reason

Can you say more about the steps you're doing that trigger this?  e.g. going through the password reset flow?

**Comment by philbooth** [comment]
Pure speculation, but we wonder if this could be related to the lack of transactions in the memory backend? If a request fails part-way through there, it will leave the memory store in a weird state.

**Comment by philbooth** [comment]
> Can you say more about the steps you're doing that trigger this? e.g. going through the password reset flow?

Yep, just going through the password reset flow as a user. It took me a few goes to make it happen. The next time I tried I managed ten attempts without it happening.

Based on the murmurings drifting across the partition from @shane-tomlinson's direction, I believe we may be close to understanding it.

**Comment by rfk** [comment]
> In the auth server logs, the uid in the failing request payload is always a null byte / 00

I believe I've seen this in other auth-server logs as some sort of default value, e.g. in the summary logs for /account/create where we didn't actually have the uid when the log was emitted.

**Comment by shane-tomlinson** [comment]
I believe the problem is...drum roll...  the passwordForgotToken is [created with the same createdAt as the EmailRecord](https://github.com/mozilla/fxa-auth-server/blob/80aa280e1eec14ce28763fcb92fa49fa4f8da248/lib/db.js#L172). The emailRecord's createdAt is [propagated to the accountResetToken](https://github.com/mozilla/fxa-auth-server/blob/80aa280e1eec14ce28763fcb92fa49fa4f8da248/lib/db.js#L146). For local dev, [ttl for a passwordForgotToken is 60 mins and for an accountResetToken 15 mins](https://github.com/mozilla/fxa-auth-server/blob/80aa280e1eec14ce28763fcb92fa49fa4f8da248/config/index.js#L254:L268). If the account is more than 60 minutes old, password reset "start" fails. If the account is more than 15 minutes old but less than 60 minutes old, password reset "start" succeeds, but account reset fails. BAM!

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/3831

**Comment by rfk** [comment]
epic sleuthing guys!

**Comment by philbooth** [comment]
Closing this in favour of https://github.com/mozilla/fxa-auth-server/issues/1373, which is in the correct repo. I've copied @shane-tomlinson's triumphant Sherlock Holmes moment over to that issue.

**Comment by vbudhram** [comment]
Awesome detective 🔎 work!
