### ISSUE TITLE
query in prune_4

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-db-mysql#278]
I turned the first of the deletes into a select and explain'ed it (below). Currently running the select in stage, and it's still thinking about it at 45 minutes.
```
mysql> explain select from_unixtime(createdAt/1000) as creat FROM sessionTokens WHERE createdAt < 1437780208129 AND NOT EXISTS (SELECT d.sessionTokenId FROM devices AS d WHERE d.sessionTokenId = sessionTokens.tokenId) ORDER BY createdAt LIMIT 10000;

+----+--------------------+---------------+-------+---------------+---------------------------+---------+------+------+-----------------------------+
| id | select_type        | table         | type  | possible_keys | key                       | key_len | ref  | rows | Extra                       |
+----+--------------------+---------------+-------+---------------+---------------------------+---------+------+------+-----------------------------+
|  1 | PRIMARY            | sessionTokens | ALL   | NULL          | NULL                      | NULL    | NULL |    3 | Using where; Using filesort |
|  2 | DEPENDENT SUBQUERY | d             | index | NULL          | UQ_devices_sessionTokenId | 49      | NULL |    5 | Using where; Using index    |
+----+--------------------+---------------+-------+---------------+---------------------------+---------+------+------+-----------------------------+
2 rows in set (0.00 sec)
```

**Comment by rfk** [comment]
Hrm, this is a thorny problem.  For reference the current query is:

```
DELETE FROM sessionTokens
    WHERE createdAt < olderThan
    AND NOT EXISTS (
      SELECT d.sessionTokenId
      FROM devices AS d
      WHERE d.sessionTokenId = sessionTokens.tokenId
    )
    ORDER BY createdAt
    LIMIT 10000;
```

Since this has `ORDER BY createdAt`, and we don't have an index on `createdAt`, it needs to do a full table scan and spill all the rows to disk in sorted order, in order to find the 10000 that it wants to delete.

Adding an index on `createdAt` will help here, but may not be enough because of the subquery.  Imagine that we have 3 million rows in this table, and those with the two million earliest `createdAt` dates all have a device record and hence cannot be deleted.  In order to find the tokens to delete, MySQL will have to walk the `createdAt` index in sorted order, examine all two million of the oldest session tokens that have device records to establish that they shouldn't be deleted, and then finally start examining the newer rows for things it can delete.

What might work here is querying with a sliding window of `newerThan` and `olderThan`, telling MySQL to delete `WHERE createdAt > newerThan AND createdAt < olderThan` and thus examine only a small slice of the table.  But we'd need some out-of-band way to know that all tokens earlier than `newerThan` have already been examined for pruning.  Store a timestamp in the db metadata table maybe?

**Comment by philbooth** [comment]
It seems like I'm making no progress over in #279 and we're almost at train-cutting time. Should I create a migration that reverts back to the `prune_4` state so that we can reinstate pruning on the other tokens for train 96?

**Comment by philbooth** [comment]
(by which I really mean, "progresses to the `prune_6` state that is identical to the `prune_4` state)

**Comment by rfk** [comment]
> (by which I really mean, "progresses to a prune_6 state that is identical to the prune_4 state")

👍
