### ISSUE TITLE
Reinstate the upsertAvailableCommands stored procedure

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#384]
We need to revert this abomination:

https://github.com/mozilla/fxa-auth-db-mysql/commit/06554f5599fb167bcdf79c8586f2d7c9ab87643e

...and replace it with a proper fix.

By "proper fix", I mean something that doesn't cause lock contention when the session-related stored procedures try to join with the `deviceCommands` table, which was the cause of a major outage in prod this weekend.

**Comment by vladikoff** [comment]
Thank you Phil!

**Comment by philbooth** [comment]
I know I suggest Redis for everything but, given there is already some device-related data in Redis anyway, would keeping this data in Redis instead be a reasonable approach for a "proper" fix here?

**Comment by rfk** [comment]
Hmm...not sure how to feel about redis for this, is the data in redis kind of "less permanent" or "more ephemeral" than the data in the db in some sense?  As in, losing redis is less of a disaster than losing the db?

**Comment by rfk** [comment]
This is the `EXPLAIN` from one of the queries that was taking a long time in prod, [sessionWithDevice_14](https://github.com/mozilla/fxa-auth-db-mysql/blob/master/lib/db/schema/patch-081-082.sql#L216), which tries to slurp in the device data for a given sessionToken:

```
+----+-------------+-------+-------+-----------------------------------+---------------------------+---------+------------------+------+-------------+
| id | select_type | table | type  | possible_keys                     | key                       | key_len | ref              | rows | Extra       |
+----+-------------+-------+-------+-----------------------------------+---------------------------+---------+------------------+------+-------------+
|  1 | SIMPLE      | t     | const | PRIMARY                           | PRIMARY                   | 32      | const            |    1 | NULL        |
|  1 | SIMPLE      | a     | const | PRIMARY                           | PRIMARY                   | 16      | const            |    1 | NULL        |
|  1 | SIMPLE      | e     | ref   | emails_uid                        | emails_uid                | 16      | const            |    1 | Using where |
|  1 | SIMPLE      | d     | ref   | PRIMARY,UQ_devices_sessionTokenId | UQ_devices_sessionTokenId | 49      | const,const      |    1 | Using where |
|  1 | SIMPLE      | ci    | index | PRIMARY                           | commandName               | 766     | NULL             |    1 | Using index |
|  1 | SIMPLE      | dc    | ref   | commandId                         | commandId                 | 4       | fxa.ci.commandId | 1832 | Using where |
|  1 | SIMPLE      | ut    | const | PRIMARY                           | PRIMARY                   | 32      | const            |    1 | Using where |
+----+-------------+-------+-------+-----------------------------------+---------------------------+---------+------------------+------+-------------+
```

What stands out to me about this query plan, is that it's joining first onto the `deviceCommandIdentifiers AS ci` table before joining onto the `deviceCommands AS dc` table.  So IIUC the query will be executed by doing something like this:

* Join the `sessionTokens`, `accounts`, `emails` and `devices` tables correctly to find the single `devices` row for the given tokenId.
* Join that with the `deviceCommandIdentifiers` table, considering every single row (`ref=NULL`) in order to produce a list of all possible `commandName` fields for that device.
* For each such row, join that with the `deviceCommands` table by matching on `commandId` to find all possible device-ids that have registered that command.
* Filter that by comparing to the device-id found in the first step above.

As you can imagine, this is a suboptimal way to calculate the desired result set!  It does a full scan of the `deviceCommands` table every time we check a sessionToken, which would explain why the problem only manifest as more devices registered commands for themselves.

I think MySQL is choosing this kooky plan because the primary key for the `deviceCommands` table is `(uid, deviceId, commandId)`:

  https://github.com/mozilla/fxa-auth-db-mysql/blob/master/lib/db/schema/patch-081-082.sql#L30

But the join onto `deviceCommands` only specifies `ON dc.deviceId = d.deviceId`:

  https://github.com/mozilla/fxa-auth-db-mysql/blob/master/lib/db/schema/patch-081-082.sql#L264

Since MySQL can't assume that the userid matches whenever the deviceid matches, it can't use the primary key index to evaluate this join, and it falls back to an index that it does have (the one for the foreign key on `commandId`).

I suspect that modifying the join onto `deviceCommands` to use `ON  dc.uid = d.uid AND dc.deviceId = d.id` will fix the performance problems here.

To be sure, we'll need to figure out how to reproduce the problem in a dev environment.  My initial attempts to do so haven't been successful, but I'll keep poking at it.

**Comment by vladikoff** [comment]
[Current Query (running on latest)](https://gist.github.com/vladikoff/595987af263edef77daa0ec35b048448):

<img width="1203" alt="before" src="https://user-images.githubusercontent.com/128755/44436759-e6b9c300-a584-11e8-9159-522ab3b4cbe8.png">


@rfk Query: 

<img width="1254" alt="after" src="https://user-images.githubusercontent.com/128755/44436764-f6d1a280-a584-11e8-9e33-09ca6a79c6c2.png">

**Comment by vladikoff** [comment]
The  🔴  red full index might be an indicator of things to watch out for

**Comment by rfk** [comment]
Following @jbuck's suggestion, I think I've reproduced the troublesome behaviour in a dev environment using this script:

  https://gist.github.com/rfk/4d25dbf23ff26a3e9a1e6bd6a5471a97

I first ran a tight loop of session and device registrations to populate the db:

```
mysql> select count(*) from sessionTokens;
+----------+
| count(*) |
+----------+
|     2281 |
+----------+
1 row in set (0.00 sec)

mysql> select count(*) from devices;
+----------+
| count(*) |
+----------+
|     2274 |
+----------+
1 row in set (0.00 sec)

mysql> select count(*) from deviceCommands;
+----------+
| count(*) |
+----------+
|     2162 |
+----------+
1 row in set (0.01 sec)
```

I then created a new stored procedure `sessionWithDevice_14_fixed` using the fix described above.

I could then use the above script to run the stored procedure a bunch of times concurrently, while monitoring MySQL CPU usage.  For the original procedure, I got results like the following:

```
$ python lots_of_session_queries.py sessionWithDevice_14
Trying 10 concurrent runs of 1000 calls to sessionWithDevice_14
Time elapsed:  20.40s
MySQL CPU use: 149.7%
```

While the fixed procedure was much faster and used less CPU:

```
$ python lots_of_session_queries.py sessionWithDevice_14_fixed
Trying 10 concurrent runs of 1000 calls to sessionWithDevice_14_fixed
Time elapsed:  7.97s
MySQL CPU use: 59.9%
```

I then deleting some of the `deviceCommands` entries:

```
mysql> delete from deviceCommands limit 1000;
Query OK, 1000 rows affected (0.01 sec)

mysql> select count(*) from deviceCommands;
+----------+
| count(*) |
+----------+
|     1162 |
+----------+
1 row in set (0.00 sec)
```

Which made the original query run faster:

```
$ python lots_of_session_queries.py sessionWithDevice_14
Trying 10 concurrent runs of 1000 calls to sessionWithDevice_14
Time elapsed:  14.69s
MySQL CPU use: 119.9%
```

But did not affect the performance of the fixe query.

I then deleted *all* the `deviceCommands` entries:

```
mysql> delete from deviceCommands;
Query OK, 1162 rows affected (0.01 sec)

mysql> select count(*) from deviceCommands;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
```

Which allowed the original query to run with pretty much the same resource usage as the fixed query:

```
$ python lots_of_session_queries.py sessionWithDevice_14
Trying 10 concurrent runs of 1000 calls to sessionWithDevice_14
Time elapsed:  7.97s
MySQL CPU use: 59.9%
$
$ python lots_of_session_queries.py sessionWithDevice_14_fixed
Trying 10 concurrent runs of 1000 calls to sessionWithDevice_14_fixed
Time elapsed:  7.86s
MySQL CPU use: 59.9%
```

So I think we can be confident that we've identified the source of the performance problems in production.
