### ISSUE TITLE
Check for `using where` in stored procedure lint script

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#420]
From https://github.com/mozilla/fxa-content-server/issues/6655#issuecomment-434021394:

> So, instead of `using index` or `using index condition`, `using where`.

Currently the lint script is checking for `using where`, but that can easily be addressed.

**Comment by rfk** [comment]
It's not clear to me whether `using where` always indicates a problem.  In the query plan in https://github.com/mozilla/fxa-content-server/issues/6655#issuecomment-434021394 the `using where` row looks like:

```
| id | select_type | table  | type  | possible_keys   | key             | key_len | ref   | rows | Extra       |
|  1 | PRIMARY     | e      | ref   | emails_uid      | emails_uid      | 16      | const |    1 | Using where |
```

It's using the `emails_uid` index to limit its search to only the selected uid, as we intend.  It then has to load each of those rows in order to check their `isPrimary` column and filter down to just the primary address.  The only way to get rid of the `using where` here would be to include `isPrimary` as an additional column in the `emails_uid` index, which seems like it would be overkill just to avoid loading a handful of rows.

**Comment by philbooth** [comment]
> It's not clear to me whether `using where` always indicates a problem.

Understood, closing this in that case!
