### ISSUE TITLE
Refactor our fragile cross-repo dependency setup

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#54]
Comments like https://github.com/mozilla/fxa-auth-server/pull/954 and https://github.com/mozilla/fxa-auth-db-mysql/issues/51#issuecomment-110996075 make me sad.  The current factoring of these auth-db-* repos seems to be creating a lot of busywork and deployment footguns.  Let's find a better way to do this.

I personally lean towards "squash them all back together into a single repo" like the way oauth-server does its backends, but am open to other suggestions :-)

**Comment by chilts** [comment]
Are suggesting a merge of `fxa-auth-db-*` AND `fxa-auth-server` together ... or just the three `fxa-auth-db-*` repos together? I'd prefer the latter since then it still separates the auth-db-server from the auth-server which I think is important.

I'm not averse to the idea of squishing the repos together.

One reason it was good to separate out the backends was so that in dev (and things like fxa-local-dev) we didn't have to install the `mysql` backend dependencies. I can see this point but I guess we question whether it's not actually that big anyway. Otherwise we could investigate npm's `optionalDepedencies` and how that works with shrinkwrap, though I'm not holding out hope for an easy ride there. Just putting out some initial thoughts here and see what others think.

**Comment by rfk** [comment]
> just the three fxa-auth-db-* repos together

This, at least as a start.  I don't wanna get too carried away here :-)

> One reason it was good to separate out the backends was so that in dev
> (and things like fxa-local-dev) we didn't have to install the mysql backend dependencies.

True, but AFAIK nobody has complained about this in e.g. the oauth-server (I'd be happy to be informed to the contrary though).

**Comment by chilts** [comment]
Yeah, I don't think anyone has complained, but I think it was stated as an advantage when we separated them out so just thought I'd re-state it here. :)

**Comment by rfk** [comment]
Per IRL discussion, yes, let's squish them all together into a single repo.  We may still keep them as separate "packages" with their own `package.json` file if that's valuable for publishing on npm.
