### ISSUE TITLE
Process new retention metrics in a Heka filter

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#86]
Part of https://github.com/mozilla/fxa/issues/45.

This work will actually be done in [`mozilla-services/puppet-config`](https://github.com/mozilla-services/puppet-config), but I'm raising the issue here to give it visibility in our planning process.

Post- ~~https://github.com/mozilla/fxa-auth-db-mysql/issues/85~~ https://github.com/mozilla/fxa-auth-server/issues/1027, we'll need a new Heka filter to turn the account activity metrics into datapoints for the new retention graph(s).

**Comment by rfk** [comment]
IIRC I was assigned to this to add a bit of context on the filter I was using for sync, so here it is for posterity:

  https://github.com/mozilla-services/puppet-config/pull/1515/f

That does daily retention counts based on a `created_at` timestamp included with each log entry.  We could do a similar approach as a first pass for FxA, but possibly using weeks instead of days (or even both).

Unassigning myself for now while we figure out more details of the approach we're going to go forward with.

**Comment by vladikoff** [comment]
> Unassigning myself for now while we figure out more details of the approach we're going to go forward with.

We will be processing using http://telemetry-dash.mozilla.org/ + Spark 

Repo: https://github.com/vladikoff/fxa-retention-ipynb
Data Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1207015
