### ISSUE TITLE
Provide API for listing session tokens

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#98]
Let's provide an API for listing all session tokens active on an account.  I'm thinking as simple as:

  `GET /account/:id/sessions` => `[ {session data}, {session data}, ...]`

Most immediately, we'll want to be able to determine whether a user is single-device or multi-device, which can be accomplished by counting their session tokens.  We'll eventually want to display session tokens and their metadata on a control dashboard.

One thing to be careful of: we probably *dont* want to return the token's secret data in this query, to guard against accidental leakage.  You should only get at that data if you look up a session directly by its id.

**Comment by philbooth** [comment]
@dannycoates, as per https://github.com/mozilla/fxa-auth-server/issues/1038#issuecomment-139118925, I'm implementing this locally so that I can test some auth server changes that depend on it.

I'm also happy to do it properly (i.e. write tests) and open a PR but, as this is your issue, I definitely won't do that unless you explicitly write the words `Do it, Phil` in response to this comment. :grin:
